controllers/adm_c.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from models.adm import Adm
from utils import db

bp_adm = Blueprint('adm', __name__, template_folder='../templates')

@bp_adm.route('/create', methods=['GET', 'POST'])
def create():
    if request.method == 'POST':
        nome = request.form['nome']
        email = request.form['email']
        senha = request.form['senha']
        novo = Adm(nome, email, senha)
        db.session.add(novo)
        db.session.commit()
        flash('Adm criado com sucesso!')
        return redirect(url_for('index'))
    return render_template('create_adm.html')

@bp_adm.route('/recovery')
def recovery():
    adm = Adm.query.all()
    return render_template('recovery_adm.html', adm=adm)

@bp_adm.route('/update/<int:id>', methods=['GET', 'POST'])
def update(id):
    adm = Adm.query.get(id)
    if request.method == 'POST':
        adm.nome = request.form['nome']
        adm.email = request.form['email']
        if request.form['senha']:
            adm.senha = request.form['senha']
        db.session.commit()
        flash('Adm atualizado!')
        return redirect(url_for('adm.recovery'))
    return render_template('update_adm.html', adm=adm)

@bp_adm.route('/delete/<int:id>', methods=['GET', 'POST'])
def delete(id):
    adm = Adm.query.get(id)
    if request.method == 'POST':
        db.session.delete(adm)
        db.session.commit()
        flash('Adm excluído!')
        return redirect(url_for('adm.recovery'))
    return render_template('delete_adm.html', adm=adm)

@bp_adm.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form['email']
        senha = request.form['senha']
        adm = Adm.query.filter_by(email=email, senha=senha).first()
        if adm:
            session['adm_id'] = adm.id
            session['adm_nome'] = adm.nome
            flash('Login realizado!')
            return redirect(url_for('adm.perfil'))
        flash('Credenciais inválidas')
    return render_template('login.html')

@bp_adm.route('/logout')
def logout():
    session.clear()
    flash('Logout efetuado')
    return redirect(url_for('adm.login'))

@bp_adm.route('/perfil')
def perfil():
    if 'adm_id' not in session:
        flash('Faça login primeiro')
        return redirect(url_for('adm.login'))
    adm = Adm.query.get(session['adm_id'])
    return render_template('perfil_adm.html', adm=adm)

controllers/usuario_c.py
from flask import render_template, request, redirect, flash, Blueprint, url_for, session
from models.usuario import Usuario
from utils import db

bp_usuarios = Blueprint("usuarios", __name__, template_folder='../templates')

@bp_usuarios.route('/recovery')
def recovery():
    usuarios = Usuario.query.all()
    return render_template('recovery.html', usuarios = usuarios)

@bp_usuarios.route('/create', methods=['GET','POST'])
def create():
    if request.method=='POST':
        nome = request.form.get('nome')
        email = request.form.get('email')
        senha = request.form.get('senha')
        novo = Usuario(nome, email, senha)
        db.session.add(novo)
        db.session.commit()
        flash('Dados cadastrados com sucesso!')
        return redirect(url_for('usuarios.recovery'))
    return render_template('create.html')
    
@bp_usuarios.route('/update/<int:id>', methods=['GET','POST'])
def update(id):
    usuario = Usuario.query.get(id)
    if request.method=='POST':
        usuario.nome = request.form['nome']
        usuario.email = request.form['email']
        if request.form['senha']:
            usuario.senha = request.form['senha']
        db.session.commit()
        flash("Dados atualizados!")
        return redirect(url_for('usuarios.recovery'))
    return render_template('update.html', usuario = usuario)

@bp_usuarios.route('/delete/<int:id>', methods=['GET','POST'])
def delete(id):
    usuario = Usuario.query.get(id)
    if request.method == 'POST':
        db.session.delete(usuario)
        db.session.commit()
        flash('Usuário excluído com sucesso')
        return redirect(url_for('usuarios.recovery'))
    return render_template('delete.html', usuario = usuario)

@bp_usuarios.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form['email']
        senha = request.form['senha']
        usuario = Usuario.query.filter_by(email=email, senha=senha).first()
        if usuario:
            session['usuario_id'] = usuario.id
            session['usuario_nome'] = usuario.nome
            flash('Login realizado!')
            return redirect(url_for('usuarios.perfil'))
        flash('Credenciais inválidas')
    return render_template('login.html')

@bp_usuarios.route('/logout')
def logout():
    session.clear()
    flash('Logout efetuado')
    return redirect(url_for('usuarios.login'))

@bp_usuarios.route('/perfil')
def perfil():
    if 'usuario_id' not in session:
        flash('Faça login primeiro')
        return redirect(url_for('usuarios.login'))
    usuario = Usuario.query.get(session['usuario_id'])
    return render_template('perfil.html', usuario=usuario)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
    <link rel='stylesheet' href="{{ url_for('static', filename='css/style.css') }}">
    <link href='https://fonts.googleapis.com/css?family=Aldrich' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Anta' rel='stylesheet'>
    {% block titulo %}
    {% endblock %}
</head>
<body>
    {% block audio %}
    {% endblock %}
    <header>
        {% block logo %}
        {% endblock %}
        <br>
        <h1>Bem-vinde ao Digimundo!</h1>
        <p class="subtexto">Aproveite a estadia</p>
            <nav>
            <ul>
                <li>
                <a class="navbar-brand" href="/">
                    <img src="../static/imgs/logo/logo_digi.gif" alt="Logo" width="30" height="24" class="d-inline-block align-text-top">
                    <span class='brand-text'>Digimundo</span>
                </a>
            </li>
            {% block nav %}
            {% endblock %}
            {% if session.get('usuario_id') %}
                <li><a href="{{ url_for('usuarios.perfil') }}">Perfil</a></li>
            {% elif session.get('adm_id') %}
                <li><a href="{{ url_for('adm.perfil') }}">Perfil</a></li>
            {% else %}
                <li><a href="/conta">Conta</a></li>
            {% endif %}
            </ul>
            </nav>
    </header>
    <main>
        {% block main %}
        {% endblock %}
    </main>
    <footer>
        <p class="subtexto">Todos os direitos vão para Toei Animation e relacionados</p>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js" integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.min.js" integrity="sha384-RuyvpeZCxMJCqVUGFI0Do1mQrods/hhxYlcVfGPOfQtPJh0JCw12tUAZ/Mv10S7D" crossorigin="anonymous"></script>
</body>
</html>

templates/create.html
{% extends 'base.html' %}

{% block titulo %}
    <title>Digimundo - Página Inicial</title>
{% endblock %}

{% block logo %}
    <div class="logo">
        <img src="../static/imgs/logo/logo.png">
    </div>
{% endblock %}

{% block audio %}
    <audio autoplay loop>
        <source src="{{ url_for('static', filename='audio/bolero.mp3') }}" type='audio/mpeg'>
    </audio>
{% endblock %}

{% block main %}
  <h2>Cadastro</h2>
  <form method="POST">
      Nome: <input type="text" name="nome" required maxlength="20"><br>
      Email: <input type="email" name="email" required maxlength="30"><br>
      Senha: <input type="password" name="senha" class="form-control"
      required pattern="\d{1,10}" maxlength="10" size="10"><br>
      <button type="submit">Cadastrar</button>
  </form>
  <br>
  <a href="{{ url_for('usuarios.recovery') }}">Voltar</a>
{% endblock %}

templates/create_adm.html
{% extends 'base.html' %}

{% block titulo %}
    <title>Digimundo - Página Inicial</title>
{% endblock %}

{% block logo %}
    <div class="logo">
        <img src="../static/imgs/logo/logo.png">
    </div>
{% endblock %}

{% block audio %}
    <audio autoplay loop>
        <source src="{{ url_for('static', filename='audio/bolero.mp3') }}" type='audio/mpeg'>
    </audio>
{% endblock %}

{% block main %}
  <h2>Cadastro de ADM</h2>
  <form method="POST">
      Nome: <input type="text" name="nome" required maxlength="20"><br>
      Email: <input type="email" name="email" required maxlength="30"><br>
      Senha: <input type="password" name="senha" class="form-control"
      required pattern="\d{1,10}" maxlength="10" size='10'><br>
      <button type="submit">Cadastrar</button>
  </form>
  <br>
  <a href="{{ url_for('adm.recovery') }}">Voltar</a>
{% endblock %}

templates/delete.html
{% extends 'base.html' %}

{% block titulo %}
    <title>Digimundo - Página Inicial</title>
{% endblock %}

{% block logo %}
    <div class="logo">
        <img src="../static/imgs/logo/logo.png">
    </div>
{% endblock %}

{% block audio %}
    <audio autoplay loop>
        <source src="{{ url_for('static', filename='audio/bolero.mp3') }}" type='audio/mpeg'>
    </audio>
{% endblock %}

{% block main %}

  <h2>Excluir Usuário</h2>
  <p>Tem certeza que deseja excluir o usuário {{ usuario.nome }}?</p><br>
  <form method="POST">
      <button type="submit">Confirmar</button><br>
      <a href="{{ url_for('usuarios.recovery') }}">Cancelar</a>
  </form>

{% endblock%}

templates/delete_adm.html
{% extends 'base.html' %}

{% block titulo %}
    <title>Digimundo - Página Inicial</title>
{% endblock %}

{% block logo %}
    <div class="logo">
        <img src="../static/imgs/logo/logo.png">
    </div>
{% endblock %}

{% block audio %}
    <audio autoplay loop>
        <source src="{{ url_for('static', filename='audio/bolero.mp3') }}" type='audio/mpeg'>
    </audio>
{% endblock %}

{% block main %}

  <h2>Excluir ADM</h2>
  <p>Tem certeza que deseja excluir o ADM {{ adm.nome }}?</p><br>
  <form method="POST">
      <button type="submit">Confirmar</button><br>
      <a href="{{ url_for('adm.recovery') }}">Cancelar</a>
  </form>

{% endblock%}

templates/escolha_cadastro.html
{% extends 'base.html' %}

{% block titulo %}
    <title>Digimundo - Página Inicial</title>
{% endblock %}

{% block logo %}
    <div class="logo">
        <img src="../static/imgs/logo/logo.png">
    </div>
{% endblock %}

{% block audio %}
    <audio autoplay loop>
        <source src="{{ url_for('static', filename='audio/bolero.mp3') }}" type='audio/mpeg'>
    </audio>
{% endblock %}

{% block main %}

    <h2>Qual tipo de conta você quer criar?</h2>
    <div class="d-flex flex-row align-items-center justify-content-center">
        <div class='foto'>
            <a href="{{url_for('adm.create')}}" class="btn img-button digi-btn digi-img-1"></a>
            <p class='subtexto'>Administrador</p>
        </div>
        <div>
            <a href="{{url_for('usuarios.create')}}" class="btn img-button digi-btn digi-img-2"></a>
            <p class="subtexto">Usuário</p>
        </div>
    </div>

{% endblock %}

templates/escolha_delete.html
{% extends 'base.html' %}

{% block titulo %}
    <title>Digimundo - Página Inicial</title>
{% endblock %}

{% block logo %}
    <div class="logo">
        <img src="../static/imgs/logo/logo.png">
    </div>
{% endblock %}

{% block audio %}
    <audio autoplay loop>
        <source src="{{ url_for('static', filename='audio/bolero.mp3') }}" type='audio/mpeg'>
    </audio>
{% endblock %}

{% block main %}

    <h2>Qual tipo de conta você quer deletar?</h2>
    <div class="d-flex flex-row align-items-center justify-content-center">
        <div>
            <a href="{{url_for('adm.recovery')}}" class="btn img-button digi-btn digi-img-1"></a>
            <p class="subtexto">Administrador</p>
        </div>
        <div>
            <a href="{{url_for('usuarios.recovery')}}" class="btn img-button digi-btn digi-img-2"></a>
            <p class='subtexto'>Usuário</p>
        </div>
    </div>

{% endblock %}

templates/escolha_login.html
{% extends 'base.html' %}

{% block titulo %}
    <title>Digimundo - Página Inicial</title>
{% endblock %}

{% block logo %}
    <div class="logo">
        <img src="../static/imgs/logo/logo.png">
    </div>
{% endblock %}

{% block audio %}
    <audio autoplay loop>
        <source src="{{ url_for('static', filename='audio/bolero.mp3') }}" type='audio/mpeg'>
    </audio>
{% endblock %}

{% block main %}

    <h2>Qual tipo de conta você quer usar?</h2>
    <div class="d-flex flex-row align-items-center justify-content-center">
        <div>
            <a href="{{url_for('adm.login')}}" class="btn img-button digi-btn digi-img-1"></a>
            <p class='subtexto'>Administrador</p>
        </div>
        <div>
            <a href="{{url_for('usuarios.login')}}" class="btn img-button digi-btn digi-img-2"></a>
            <p class="subtexto">Usuário</p>
        </div>
    </div>

{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block titulo %}
    <title>Digimundo - Página Inicial</title>
{% endblock %}

{% block logo %}
    <div class="logo">
        <img src="../static/imgs/logo/logo.png">
    </div>
{% endblock %}

{% block audio %}
    <audio autoplay loop>
        <source src="{{ url_for('static', filename='audio/bolero.mp3') }}" type='audio/mpeg'>
    </audio>
{% endblock %}
    
{% block main %}
    <h1>O Mundo Digital</h1>
    <p>Digimon é uma franquia que ultrapassou ou bichinhos digitais e ingressou no mundo dos animes em 1999, e desde então possui novas temproadas, filmes, OVAs e muito mais!</p><br>
    <div class="d-flex flex-column align-items-center justify-content-center">
        <p>Quer aprender mais sobre uma temporada específica? Escolha abaixo:</p><br>
        <div class="d-flex flex-row align-items-center">
            <a href="/adventure" class="btn img-button bg-img-1"></a><br>
            <a href="/02" class="btn img-button bg-img-2"></a><br>
            <a href='/tamers' class="btn img-button bg-img-3"></a><br>
        </div> <br>
        <div class="d-flex flex-row align-items-center">
            <a href='/frontier' class="btn img-button bg-img-4"></a><br>
            <a href="/savers" class="btn img-button bg-img-5"></a><br>
            <a href="/ghost" class="btn img-button bg-img-6"></a>
        </div>
    </div><br>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block titulo %}
    <title>Digimundo - Página Inicial</title>
{% endblock %}

{% block logo %}
    <div class="logo">
        <img src="../static/imgs/logo/logo.png">
    </div>
{% endblock %}

{% block audio %}
    <audio autoplay loop>
        <source src="{{ url_for('static', filename='audio/bolero.mp3') }}" type='audio/mpeg'>
    </audio>
{% endblock %}

{% block main %}

  <h2>Login</h2>
  <form method="POST">
      Email: <input type="email" name="email" required maxlength="30"><br>
      Senha: <input type="password" name="senha" class="form-control"
      required pattern="\d{1,10}" maxlength="10"><br>
      <button type="submit">Entrar</button>
  </form>

{% endblock %}

templates/perfil_adm.html
{% extends 'base.html' %}

{% block titulo %}
    <title>Digimundo - Página Inicial</title>
{% endblock %}

{% block logo %}
    <div class="logo">
        <img src="../static/imgs/logo/logo.png">
    </div>
{% endblock %}

{% block audio %}
    <audio autoplay loop>
        <source src="{{ url_for('static', filename='audio/bolero.mp3') }}" type='audio/mpeg'>
    </audio>
{% endblock %}

{% block main %}

    <h2>Perfil do ADM</h2>

    <div class="amostra">
        <div class="bloco">
            <div class="foto">
                <img src="../static/imgs/digitama.png">
            </div>
            <div class="wiki">
                <p><strong>ID:</strong> {{ adm.id }}</p>
                <p><strong>Nome:</strong> {{ adm.nome }}</p>
                <p><strong>Email:</strong> {{ adm.email }}</p><br>
                <a href="{{ url_for('adm.update', id=adm.id)}}">Editar Perfil</a><br>
                <a href='/escolha_delete'>Gerenciamento de Contas</a><br>
                <a href="{{ url_for('adm.logout') }}">Sair</a>
            </div>
        </div>
    </div>

{% endblock %}

templates/recovery_adm.html
{% extends 'base.html' %}

{% block titulo %}
    <title>Digimundo - Página Inicial</title>
{% endblock %}

{% block logo %}
    <div class="logo">
        <img src="../static/imgs/logo/logo.png">
    </div>
{% endblock %}

{% block audio %}
    <audio autoplay loop>
        <source src="{{ url_for('static', filename='audio/bolero.mp3') }}" type='audio/mpeg'>
    </audio>
{% endblock %}

{% block main %}

	<h2>Lista de Adm</h2>
	<ul>
	{% for u in adm %}
		<li>
			{{ u.nome }} - {{ u.email }}
			[<a href="{{ url_for('adm.update', id=u.id) }}">Editar</a>]
			[<a href="{{ url_for('adm.delete', id=u.id) }}">Excluir</a>]
		</li>
	{% endfor %}
	</ul>

{% endblock %}

templates/update.html
{% extends 'base.html' %}

{% block titulo %}
    <title>Digimundo - Página Inicial</title>
{% endblock %}

{% block logo %}
    <div class="logo">
        <img src="../static/imgs/logo/logo.png">
    </div>
{% endblock %}

{% block audio %}
    <audio autoplay loop>
        <source src="{{ url_for('static', filename='audio/bolero.mp3') }}" type='audio/mpeg'>
    </audio>
{% endblock %}

{% block main %}
    <h2>Atualizar Dados</h2>
    <form method="POST">
        Nome: <input type="text" name="nome" value="{{ usuario.nome }}" required maxlength="10"><br>
        Email: <input type="email" name="email" value="{{ usuario.email }}" required><br>
        Nova Senha: <input type="password" name="senha" class="form-control"
      required pattern="\d{1,10}" maxlength="10"><br>
        <button type="submit">Atualizar</button>
    </form>
    <br>
    <a href="{{ url_for('usuarios.perfil') }}">Voltar</a>
{% endblock %}

templates/update_adm.html
{% extends 'base.html' %}

{% block titulo %}
    <title>Digimundo - Página Inicial</title>
{% endblock %}

{% block logo %}
    <div class="logo">
        <img src="../static/imgs/logo/logo.png">
    </div>
{% endblock %}

{% block audio %}
    <audio autoplay loop>
        <source src="{{ url_for('static', filename='audio/bolero.mp3') }}" type='audio/mpeg'>
    </audio>
{% endblock %}

{% block main %}
    <h2>Atualizar Dados</h2>
    <form method="POST">
        Nome: <input type="text" name="nome" value="{{ adm.nome }}" required maxlength="10"><br>
        Email: <input type="email" name="email" value="{{ adm.email }}" required><br>
        Nova Senha: <input type="password" name="senha" class="form-control"
      required pattern="\d{1,10}" maxlength="10"><br>
        <button type="submit">Atualizar</button>
    </form>
    <br>
    <a href="{{ url_for('adm.perfil') }}">Voltar</a>
{% endblock %}